openapi: 3.0.0
info:
  title: shared
  version: 0.0.1

paths: {}

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    APIError:
      description: defines the structure of an API error response
      type: object
      properties:
        message:
          type: string
          x-go-type: interface{}
        code:
          type: integer
        internal:
          type: string
          x-go-type: error
          x-go-json-ignore: true
        errors:
          type: object
          x-go-type: ErrorMap
      required:
        - message
        - code
        - internal

  responses:
    # Status code 400
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"

    # Status code 401
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"

    # Status code 404
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"

    # Status code 500
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"
