/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserToTeamRequest
 */
export interface AddUserToTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof AddUserToTeamRequest
     */
    teamId: string;
}

/**
 * Check if a given object implements the AddUserToTeamRequest interface.
 */
export function instanceOfAddUserToTeamRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "teamId" in value;

    return isInstance;
}

export function AddUserToTeamRequestFromJSON(json: any): AddUserToTeamRequest {
    return AddUserToTeamRequestFromJSONTyped(json, false);
}

export function AddUserToTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToTeamRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': json['team_id'],
    };
}

export function AddUserToTeamRequestToJSON(value?: AddUserToTeamRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'team_id': value.teamId,
    };
}

