/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAPIKeyResponse
 */
export interface CreateAPIKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAPIKeyResponse
     */
    key?: string;
}

/**
 * Check if a given object implements the CreateAPIKeyResponse interface.
 */
export function instanceOfCreateAPIKeyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateAPIKeyResponseFromJSON(json: any): CreateAPIKeyResponse {
    return CreateAPIKeyResponseFromJSONTyped(json, false);
}

export function CreateAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function CreateAPIKeyResponseToJSON(value?: CreateAPIKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

