/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterationRequest
 */
export interface RegisterationRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterationRequest
     */
    teamName: string;
}

/**
 * Check if a given object implements the RegisterationRequest interface.
 */
export function instanceOfRegisterationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "teamName" in value;

    return isInstance;
}

export function RegisterationRequestFromJSON(json: any): RegisterationRequest {
    return RegisterationRequestFromJSONTyped(json, false);
}

export function RegisterationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirm_password'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'teamName': json['team_name'],
    };
}

export function RegisterationRequestToJSON(value?: RegisterationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'confirm_password': value.confirmPassword,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'team_name': value.teamName,
    };
}

