/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamUser
 */
export interface TeamUser {
    /**
     * 
     * @type {string}
     * @memberof TeamUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TeamUser
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamUser
     */
    userId: string;
    /**
     * 
     * @type {Date}
     * @memberof TeamUser
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TeamUser
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TeamUser interface.
 */
export function instanceOfTeamUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "teamId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function TeamUserFromJSON(json: any): TeamUser {
    return TeamUserFromJSONTyped(json, false);
}

export function TeamUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'userId': json['user_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function TeamUserToJSON(value?: TeamUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'team_id': value.teamId,
        'user_id': value.userId,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}

