/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Team } from './Team';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
} from './Team';

/**
 * 
 * @export
 * @interface TeamList
 */
export interface TeamList {
    /**
     * 
     * @type {Array<Team>}
     * @memberof TeamList
     */
    teams?: Array<Team>;
}

/**
 * Check if a given object implements the TeamList interface.
 */
export function instanceOfTeamList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamListFromJSON(json: any): TeamList {
    return TeamListFromJSONTyped(json, false);
}

export function TeamListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teams': !exists(json, 'teams') ? undefined : ((json['teams'] as Array<any>).map(TeamFromJSON)),
    };
}

export function TeamListToJSON(value?: TeamList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teams': value.teams === undefined ? undefined : ((value.teams as Array<any>).map(TeamToJSON)),
    };
}

