openapi: 3.0.0
info:
  title: slack
  version: 0.0.1

paths:
  /v1/slack:
    get:
      summary: Slack Oauth and save the info
      description: Slack Oauth and save the info
      operationId: slack-oauth
      tags:
        - slack
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Slack"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

components:
  schemas:
    Slack:
      type: object
      x-go-name: Slack
      x-breu-entity: slack
      x-breu-entity-type: cql
      properties:
        id:
          type: string
          format: uuid
          x-go-name: ID
          x-go-type: gocql.UUID
        channel_id:
          type: string
          x-go-name: ChannelID
        channel_name:
          type: string
          x-go-name: ChannelName
        workspace_id:
          type: string
          x-go-name: WorkspaceID
        workspace_name:
          type: string
          x-go-name: WorkspaceName
        bot_token:
          type: string
          x-go-name: BotToken
        team_id:
          type: string
          format: uuid
          x-go-name: TeamID
          x-go-type: gocql.UUID
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - channel_id
        - channel_name
        - workspace_id
        - workspace_name
        - bot_token
        - team_id
        - created_at
        - updated_at
