openapi: 3.0.0
info:
  title: slack
  version: 0.0.1

paths:
  /v1/slack:
    get:
      summary: Slack Oauth and save the info
      description: Slack Oauth and save the info
      operationId: slack-oauth
      tags:
        - slack
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "../../core/v1/components.yaml#/components/schemas/MessageProviderData"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

components:
  securitySchemes:
    BearerAuth:
      $ref: "../../shared/v1/schema.yaml#/components/securitySchemes/BearerAuth"
    APIKeyAuth:
      $ref: "../../shared/v1/schema.yaml#/components/securitySchemes/APIKeyAuth"
