openapi: 3.0.0
info:
  title: slack
  version: 0.0.1

paths:
  /v1/auth/slack/login:
    get:
      summary: Initiate slack login
      description: Slack
      operationId: login
      tags:
        - slack
      responses:
        "302":
          description: Redirects to slack login
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

  /v1/auth/slack/login/callback:
    get:
      summary: Callback after Slack login
      description: Slack Oauth Redirect
      operationId: slack-oauth

      tags:
        - slack
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SlackResponse"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

components:
  schemas:
    SlackResponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/SlackStatus"
        errors:
          type: object
          additionalProperties:
            type: string

      required:
        - status

    SlackStatus:
      type: string
      enum:
        - Ok
        - Error
