openapi: 3.0.0

info:
  title: core
  version: 0.0.1

paths:
  /core/repos:
    post:
      summary: Create repo
      description: Create repo
      operationId: create-repo
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      requestBody:
        description: Repo
        content:
          application/json:
            schema:
              $ref: "./components.yaml#/components/schemas/RepoCreateRequest"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./components.yaml#/components/schemas/Repo"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../../shared/v1/schema.yaml#/components/responses/Unauthorized"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

    get:
      summary: List Repos
      description: List Repos
      operationId: list-repos
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./components.yaml#/components/schemas/RepoListResponse"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../../shared/v1/schema.yaml#/components/responses/Unauthorized"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"
  /core/repos/{id}:
    get:
      summary: Get repo
      description: Get repo
      operationId: get-repo
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      parameters:
        - name: id
          in: path
          description: Repo ID
          required: true
          schema:
            type: string
            format: uuid
            x-go-type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./components.yaml#/components/schemas/Repo"
        "400":
          $ref: "../../shared/v1/schema.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../../shared/v1/schema.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../../shared/v1/schema.yaml#/components/responses/NotFound"
        "500":
          $ref: "../../shared/v1/schema.yaml#/components/responses/InternalServerError"

components:
  # FIXME: This should not be part of this file. Hack
  securitySchemes:
    BearerAuth:
      $ref: "../../shared/v1/schema.yaml#/components/securitySchemes/BearerAuth"
    APIKeyAuth:
      $ref: "../../shared/v1/schema.yaml#/components/securitySchemes/APIKeyAuth"
